adding unit test

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -24,3 +24,28 @@ jobs:
 #
     - name: Run linter
       run: npm run lint
+
+
+unit-tests:
+  runs-on: ubuntu-latest
+  steps:
+  - uses: actions/checkout@v3
+  - name: Use Node.js 18.x
+    uses: actions/setup-node@v3
+    with:
+      node-version: "18"
+
+# install npm dependencies
+  - name: Install dependencies
+    run: npm clean-install
+
+# running unit tests
+  - name: Run unit tests
+    run: npm run test-unit
+
+# if this succeeds or failues no matter what run next step
+  - if: success() || failure()
+    uses: actions/upload-artifact@v3
+    with:
+      name: unit-test-${{ github.sha }}
+      path: reports/report.xml
